version: '3.9'

services:
  calcpy:
    build:
      context: ./calculadora_python
      dockerfile: Dockerfile
    container_name: calcpy
    ports:
      - "5000:5000"
    networks:
      - private-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/soma?num1=1&num2=1"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    restart: always

  client:
    build:
      context: ./cliente_multithreading
      dockerfile: Dockerfile
    container_name: cliente
    networks:
      - private-net
    depends_on:
      calcpy:
        condition: service_healthy
    restart: always

networks:
  private-net:
    driver: bridge